scene:
  name: CAD Comprehensive Demo
  description: Complete demonstration of CAD features
  resolution: "1080p"
  fps: 30
  duration: 10
  background_color: "#0f0f0f"

  objects:
    # Title
    title:
      type: text
      text: "Manim CAD Features"
      params:
        color: "#FFFFFF"
        scale: 1.2
        position: [0, 3.5, 0]

    # Row 1: Shape modifications
    rounded_square:
      type: rounded_shape
      params:
        shape: square
        size: 1.5
        corner_radius: 0.3
        color: "#FF6B6B"
        stroke_width: 3
        position: [-4, 1.5, 0]

    chamfered_rect:
      type: chamfered_shape
      params:
        shape: rectangle
        width: 2
        height: 1.2
        chamfer_offset: 0.2
        color: "#4ECDC4"
        stroke_width: 3
        position: [0, 1.5, 0]

    dashed_triangle:
      type: dashed_shape
      params:
        shape: triangle
        radius: 1.0
        num_dashes: 9
        dashed_ratio: 0.7
        color: "#A8E6CF"
        stroke_width: 3
        position: [4, 1.5, 0]

    # Row 2: Hatching patterns
    hatched_circle:
      type: hatched_shape
      params:
        shape: circle
        radius: 0.8
        hatch_angle: 0.785
        hatch_spacing: 0.15
        color: "#FFE66D"
        stroke_width: 2
        position: [-4, -0.5, 0]

    hatched_square:
      type: hatched_shape
      params:
        shape: square
        size: 1.5
        hatch_angle: 2.356  # 135 degrees
        hatch_spacing: 0.2
        color: "#95E1D3"
        stroke_width: 2
        position: [0, -0.5, 0]

    hatched_polygon:
      type: hatched_shape
      params:
        shape: polygon
        n: 6
        radius: 0.8
        hatch_angle: 0
        hatch_spacing: 0.1
        color: "#F38181"
        stroke_width: 2
        position: [4, -0.5, 0]

    # Row 3: CAD objects for dimension demo
    dimension_rect:
      type: shape
      shape: rectangle
      params:
        width: 3
        height: 1
        color: "#666666"
        stroke_width: 2
        position: [-2, -2.5, 0]

    dimension_circle:
      type: shape
      shape: circle
      params:
        radius: 0.8
        color: "#666666"
        stroke_width: 2
        position: [3, -2.5, 0]

  animations:
    # Title animation
    - target: title
      type: write
      start_time: 0
      duration: 1.0

    # Row 1 animations
    - target: rounded_square
      type: fadein
      start_time: 0.5
      duration: 0.5
      
    - target: chamfered_rect
      type: fadein
      start_time: 0.7
      duration: 0.5
      
    - target: dashed_triangle
      type: fadein
      start_time: 0.9
      duration: 0.5

    # Row 2 animations
    - target: hatched_circle
      type: fadein
      start_time: 1.5
      duration: 0.5
      
    - target: hatched_square
      type: fadein
      start_time: 1.7
      duration: 0.5
      
    - target: hatched_polygon
      type: fadein
      start_time: 1.9
      duration: 0.5

    # Row 3 animations
    - target: dimension_rect
      type: fadein
      start_time: 2.5
      duration: 0.5
      
    - target: dimension_circle
      type: fadein
      start_time: 2.7
      duration: 0.5

    # Transform animations
    - target: rounded_square
      type: rotate
      start_time: 4.0
      duration: 2.0
      params:
        angle: 6.283
        
    - target: chamfered_rect
      type: scale
      start_time: 4.5
      duration: 1.5
      params:
        factor: 1.3
        
    - target: dashed_triangle
      type: rotate
      start_time: 5.0
      duration: 2.0
      params:
        angle: -3.142

    # Hatching animations
    - target: hatched_circle
      type: scale
      start_time: 6.0
      duration: 1.5
      params:
        factor: 1.5
        
    - target: hatched_square
      type: rotate
      start_time: 6.5
      duration: 1.5
      params:
        angle: 1.571
        
    - target: hatched_polygon
      type: scale
      start_time: 7.0
      duration: 1.5
      params:
        factor: 0.7