scene:
  name: "Manim Studio Clean Showcase"
  description: "A clean, properly positioned showcase"
  duration: 60
  resolution: [1920, 1080]
  fps: 60
  background_color: "#0a0a0a"
  
  objects:
    # Title at top
    - name: "main_title"
      type: "text"
      params:
        text: "MANIM STUDIO"
        font_size: 72
        gradient: ["#FFD700", "#FF6B6B", "#4ECDC4"]
        weight: "BOLD"
      position: [0, 3, 0]
      
    - name: "subtitle"
      type: "text"
      params:
        text: "Professional Animation Framework"
        font_size: 36
        color: "#CCCCCC"
      position: [0, 2, 0]
      
    # Shapes in middle row
    - name: "circle1"
      type: "shape"
      params:
        shape_type: "circle"
        radius: 1
        color: "#FF6B6B"
        fill_opacity: 0.8
        stroke_width: 3
      position: [-4, 0, 0]
      
    - name: "square1"
      type: "shape"
      params:
        shape_type: "square"
        side_length: 1.5
        color: "#4ECDC4"
        fill_opacity: 0.8
        stroke_width: 3
      position: [0, 0, 0]
      
    - name: "hexagon1"
      type: "shape"
      params:
        shape_type: "polygon"
        vertices: 6
        radius: 1
        color: "#9B59B6"
        fill_opacity: 0.8
        stroke_width: 3
      position: [4, 0, 0]
      
    # Bottom text
    - name: "demo_text"
      type: "text"
      params:
        text: "Animated with YAML"
        font_size: 24
        color: "#E74C3C"
      position: [0, -3, 0]
      
    # Final message (hidden initially)
    - name: "thank_you"
      type: "text"
      params:
        text: "Thank You!"
        font_size: 60
        gradient: ["#FFD700", "#FF6B6B", "#4ECDC4"]
        weight: "BOLD"
      position: [0, 0, 10]  # Start off-screen

  animations:
    # Opening (0-10s)
    - target: "main_title"
      type: "write"
      start_time: 0
      duration: 2
      
    - target: "subtitle"
      type: "fade_in"
      start_time: 1.5
      duration: 1.5
      
    # Shapes appear (10-20s)
    - target: "circle1"
      type: "create"
      start_time: 4
      duration: 1
      
    - target: "square1"
      type: "create"
      start_time: 4.5
      duration: 1
      
    - target: "hexagon1"
      type: "create"
      start_time: 5
      duration: 1
      
    # Shape animations (20-30s)
    - target: "circle1"
      type: "rotate"
      start_time: 8
      duration: 2
      params:
        angle: 360
        
    - target: "square1"
      type: "scale"
      start_time: 9
      duration: 2
      params:
        factor: 1.5
        
    - target: "hexagon1"
      type: "rotate"
      start_time: 10
      duration: 2
      params:
        angle: -360
        
    # Demo text (30-35s)
    - target: "demo_text"
      type: "write"
      start_time: 14
      duration: 2
      
    # Movement sequence (35-45s)
    - target: "circle1"
      type: "move"
      start_time: 18
      duration: 2
      params:
        to: [-4, -1, 0]
        
    - target: "hexagon1"
      type: "move"
      start_time: 19
      duration: 2
      params:
        to: [4, -1, 0]
        
    # Scale title (45-50s)
    - target: "main_title"
      type: "scale"
      start_time: 23
      duration: 1
      params:
        factor: 1.2
        
    # Indicate shapes (50-55s)
    - target: "circle1"
      type: "indicate"
      start_time: 26
      duration: 1
      params:
        scale_factor: 1.3
        color: "#FFFF00"
        
    - target: "square1"
      type: "indicate"
      start_time: 27
      duration: 1
      params:
        scale_factor: 1.3
        color: "#00FFFF"
        
    - target: "hexagon1"
      type: "indicate"
      start_time: 28
      duration: 1
      params:
        scale_factor: 1.3
        color: "#FF00FF"
        
    # Clear scene for finale (55-60s)
    - target: "subtitle"
      type: "fade_out"
      start_time: 32
      duration: 0.5
      
    - target: "demo_text"
      type: "fade_out"
      start_time: 32.5
      duration: 0.5
      
    - target: "circle1"
      type: "fade_out"
      start_time: 33
      duration: 0.5
      
    - target: "square1"
      type: "fade_out"
      start_time: 33.5
      duration: 0.5
      
    - target: "hexagon1"
      type: "fade_out"
      start_time: 34
      duration: 0.5
      
    - target: "main_title"
      type: "move"
      start_time: 35
      duration: 1.5
      params:
        to: [0, 5, 0]
        
    # Bring in thank you
    - target: "thank_you"
      type: "move"
      start_time: 37
      duration: 0.1
      params:
        to: [0, 0, 0]
        
    - target: "thank_you"
      type: "write"
      start_time: 38
      duration: 2
      
    # Final animations
    - target: "thank_you"
      type: "scale"
      start_time: 42
      duration: 2
      params:
        factor: 1.2
        
    - target: "main_title"
      type: "fade_out"
      start_time: 46
      duration: 1
      
    - target: "thank_you"
      type: "rotate"
      start_time: 48
      duration: 3
      params:
        angle: 360
        
    - target: "thank_you"
      type: "fade_out"
      start_time: 52
      duration: 2