# Comprehensive Manim Studio Feature Showcase
# This scene demonstrates ALL major features and capabilities

# Scene metadata
scene:
  name: ComprehensiveFeatureShowcase
  duration: 180  # 3 minutes to showcase everything
  fps: 60
  resolution: "1080p"
  background_color: "#000000"
  camera:
    type: 3d
    position: [0, 0, 5]
    phi: 0
    theta: 0
    zoom: 1
  layers:
    - name: background
      z_index: -10
    - name: main
      z_index: 0
    - name: effects
      z_index: 10
    - name: text
      z_index: 20

# 1. Basic Shapes and Text (0-15s)
objects:
  - type: Text
    id: title_text
    content: "Manim Studio"
    position: [0, 3, 0]
    scale: 2
    gradient:
      colors: ["#FF0080", "#00FF80"]
      direction: "horizontal"
    style:
      weight: bold
    layer: text

  - type: Text
    id: subtitle_text
    content: "Complete Feature Showcase"
    position: [0, 2, 0]
    scale: 1.2
    color: "#FFFFFF"
    opacity: 0.8
    layer: text

  # Basic shapes carousel
  - type: Circle
    id: circle_demo
    radius: 0.5
    position: [-3, 0, 0]
    color: "#FF0080"
    
  - type: Square
    id: square_demo
    side_length: 1
    position: [-1.5, 0, 0]
    color: "#00FF80"
    
  - type: Triangle
    id: triangle_demo
    base: 1
    height: 1
    position: [0, 0, 0]
    color: "#0080FF"
    
  - type: Star
    id: star_demo
    outer_radius: 0.6
    inner_radius: 0.3
    n_points: 5
    position: [1.5, 0, 0]
    color: "#FFFF00"
    
  - type: Polygon
    id: polygon_demo
    n_sides: 6
    radius: 0.5
    position: [3, 0, 0]
    color: "#FF00FF"

# 2. CAD Objects Section (15-30s)
  - type: cad_objects.RoundCorners
    id: cad_rounded_rect
    width: 2
    height: 1
    radius: 0.2
    position: [-2, -2, 0]
    color: "#FFFFFF"
    opacity: 0
    
  - type: cad_objects.LinearDimension
    id: cad_dimension
    start: [-3, -3, 0]
    end: [3, -3, 0]
    value: "6.0 units"
    opacity: 0
    
  - type: cad_objects.PointerLabel
    id: cad_label
    text: "Technical Drawing"
    pointer_location: [0, -2, 0]
    label_location: [2, -1, 0]
    opacity: 0

# 3. Physics Objects (30-45s)
  - type: physics_objects.SimplePendulum
    id: pendulum_demo
    length: 2
    bob_radius: 0.2
    initial_angle: 0.5
    gravity: 9.8
    damping: 0.1
    position: [-3, 1, 0]
    opacity: 0
    
  - type: physics_objects.Spring
    id: spring_demo
    rest_length: 2
    k: 10
    mass: 1
    initial_displacement: 0.5
    position: [0, 1, 0]
    opacity: 0
    
  - type: physics_objects.ProjectileMotion
    id: projectile_demo
    initial_velocity: [5, 8, 0]
    gravity: -9.8
    position: [3, -2, 0]
    trail_length: 20
    opacity: 0

# 4. Hyperplane Visualization (45-60s)
  - type: hyperplane_objects.Hyperplane
    id: hyperplane_2d
    coefficients: [1, 1]
    bias: -2
    dimension: 2
    bounds: [[-4, 4], [-4, 4]]
    opacity: 0
    
  - type: hyperplane_objects.SVMDecisionBoundary
    id: svm_demo
    support_vectors: [[-1, -1], [1, 1], [0, 1]]
    margin_width: 0.5
    opacity: 0

# 5. Visual Array (60-75s)
  - type: visual_array.VisualArray
    id: array_demo
    data: [42, 17, 255, 128, 8, 99]
    position: [0, 0, 0]
    cell_width: 0.8
    cell_height: 0.6
    spacing: 0.1
    show_indices: true
    show_labels: true
    format: "decimal"
    opacity: 0

# 6. Viral Video Components (75-90s)
  - type: viral_video_components.ViralTextEffect
    id: viral_text
    text: "MIND BLOWN"
    effect_type: "impact"
    position: [0, 0, 0]
    scale: 3
    opacity: 0
    
  - type: viral_video_components.ProductReveal
    id: product_reveal
    product_image: "assets/images/logo.png"
    reveal_type: "spiral"
    position: [0, -2, 0]
    opacity: 0

# 7. 3D Model (90-105s)
  - type: 3DModel
    id: model_demo
    file_path: "assets/models/cube.glb"
    position: [0, 0, 0]
    scale: [2, 2, 2]
    rotation: [0, 0, 0]
    material:
      color: "#FFD700"
      metallic: 0.8
      roughness: 0.2
    opacity: 0

# Timeline of animations
animations:
  # Introduction (0-5s)
  - target: title_text
    type: FadeIn
    start_time: 0
    duration: 1
    
  - target: subtitle_text
    type: FadeIn
    start_time: 0.5
    duration: 1
    
  # Basic shapes demonstration (5-15s)
  - target: [circle_demo, square_demo, triangle_demo, star_demo, polygon_demo]
    type: Create
    start_time: 5
    duration: 2
    
  - target: [circle_demo, square_demo, triangle_demo, star_demo, polygon_demo]
    type: Rotate
    start_time: 7
    duration: 3
    angle: 6.28  # Full rotation
    
  - target: [title_text, subtitle_text]
    type: FadeOut
    start_time: 13
    duration: 1
    
  - target: [circle_demo, square_demo, triangle_demo, star_demo, polygon_demo]
    type: FadeOut
    start_time: 14
    duration: 1
    
  # CAD Objects (15-30s)
  - target: cad_rounded_rect
    type: FadeIn
    start_time: 15
    duration: 1
    
  - target: cad_dimension
    type: Write
    start_time: 16
    duration: 2
    
  - target: cad_label
    type: FadeIn
    start_time: 17
    duration: 1
    
  - type: cad_effects.CADCreateEffect
    target: cad_rounded_rect
    start_time: 18
    duration: 3
    style: "blueprint"
    
  - target: [cad_rounded_rect, cad_dimension, cad_label]
    type: FadeOut
    start_time: 28
    duration: 1
    
  # Physics Simulation (30-45s)
  - target: [pendulum_demo, spring_demo]
    type: FadeIn
    start_time: 30
    duration: 1
    
  - type: physics_effects.GravityEffect
    target: pendulum_demo
    start_time: 31
    duration: 10
    gravity: 9.8
    
  - type: physics_effects.SpringForceEffect
    target: spring_demo
    start_time: 31
    duration: 10
    k: 10
    damping: 0.1
    
  - target: projectile_demo
    type: FadeIn
    start_time: 35
    duration: 1
    
  - target: [pendulum_demo, spring_demo, projectile_demo]
    type: FadeOut
    start_time: 43
    duration: 1
    
  # Hyperplane Visualization (45-60s)
  - target: hyperplane_2d
    type: FadeIn
    start_time: 45
    duration: 1
    
  - target: hyperplane_2d
    type: Transform
    start_time: 46
    duration: 3
    coefficients: [2, -1]
    bias: 0
    
  - target: svm_demo
    type: FadeIn
    start_time: 50
    duration: 1
    
  - target: [hyperplane_2d, svm_demo]
    type: FadeOut
    start_time: 58
    duration: 1
    
  # Visual Array Demo (60-75s)
  - target: array_demo
    type: FadeIn
    start_time: 60
    duration: 1
    
  - target: array_demo
    type: Transform
    start_time: 62
    duration: 2
    format: "hex"
    
  - target: array_demo
    type: Transform
    start_time: 65
    duration: 2
    format: "binary"
    
  - target: array_demo
    type: data_structure_effects.SortingAnimation
    start_time: 68
    duration: 5
    algorithm: "bubble_sort"
    
  - target: array_demo
    type: FadeOut
    start_time: 73
    duration: 1
    
  # Viral Video Effects (75-90s)
  - target: viral_text
    type: viral_effects.ViralTextAnimation
    start_time: 75
    duration: 3
    style: "glitch"
    
  - target: product_reveal
    type: viral_effects.ProductRevealAnimation
    start_time: 78
    duration: 3
    
  - type: viral_video_components.RapidTransition
    start_time: 81
    duration: 0.5
    transition_type: "glitch"
    
  - target: [viral_text, product_reveal]
    type: FadeOut
    start_time: 88
    duration: 1
    
  # 3D Model Demo (90-105s)
  - target: model_demo
    type: FadeIn
    start_time: 90
    duration: 1
    
  - target: model_demo
    type: Rotate
    start_time: 91
    duration: 10
    angle: 12.56  # Two full rotations
    axis: [0, 1, 0]
    
  - target: model_demo
    type: Scale
    start_time: 95
    duration: 3
    scale_factor: 1.5
    
  # Camera movements throughout
  - target: camera
    type: camera_movements.Orbit
    start_time: 15
    duration: 15
    center: [0, 0, 0]
    radius: 8
    phi_range: [0, 0.5]
    
  - target: camera
    type: camera_movements.DollyZoom
    start_time: 45
    duration: 5
    target_position: [0, 0, 0]
    zoom_factor: 2
    
  - target: camera
    type: camera_movements.FlyThrough
    start_time: 90
    duration: 15
    waypoints:
      - position: [5, 5, 5]
        look_at: [0, 0, 0]
      - position: [-5, 5, 5]
        look_at: [0, 0, 0]
      - position: [0, 0, 10]
        look_at: [0, 0, 0]

# Special Effects Layer
effects:
  # Glow effects on shapes
  - type: GlowEffect
    target: [circle_demo, square_demo, triangle_demo, star_demo, polygon_demo]
    start_time: 7
    duration: 5
    glow_radius: 0.3
    glow_color: "#FFFFFF"
    
  # Particle effects
  - type: ParticleSystem
    id: particles_bg
    start_time: 30
    duration: 30
    particle_count: 100
    emission_rate: 10
    lifetime: 3
    position: [0, 0, 0]
    velocity_range: [[-2, 2], [-2, 2], [-2, 2]]
    color: "#0080FF"
    size: 0.05
    layer: effects
    
  # Neon effect on viral text
  - type: NeonEffect
    target: viral_text
    start_time: 75
    duration: 10
    pulse_frequency: 2
    
  # Lens flare during 3D showcase
  - type: LensFlareEffect
    position: [5, 5, 5]
    start_time: 90
    duration: 15
    intensity: 0.8
    layer: effects
    
  # Background grid for technical feel
  - type: cad_effects.TechnicalGridEffect
    start_time: 15
    duration: 15
    grid_spacing: 0.5
    opacity: 0.2
    layer: background

# Final composition effects
post_processing:
  - type: ChromaticAberration
    strength: 0.01
    start_time: 75
    duration: 15
    
  - type: DepthOfField
    focal_distance: 5
    aperture: 0.1
    start_time: 90
    duration: 15
    
  - type: Vignette
    strength: 0.3
    start_time: 0
    duration: 180