scene:
  name: "Manim Studio Comprehensive Showcase"
  description: "Demonstrating all major features of the framework"
  duration: 120
  resolution: [1920, 1080]
  fps: 60
  background_color: "#0a0a0a"
  
  # Frame extraction for analysis
  frame_extraction:
    enabled: true
    frame_interval: 300
    analyze: true
    keyframe_extraction: true
    keyframe_threshold: 0.8
    generate_report: true

objects:
  # ============ TITLE SEQUENCE ============
  - name: "main_title"
    type: "text"
    params:
      text: "MANIM STUDIO"
      font_size: 96
      gradient: ["#FFD700", "#FF6B6B", "#4ECDC4", "#9B59B6"]
      weight: "BOLD"
    position: [0, 3, 0]
    layer: "foreground"
    
  - name: "subtitle"
    type: "text"
    params:
      text: "Professional Animation Framework"
      font_size: 48
      color: "#CCCCCC"
    position: [0, 1.5, 0]
    layer: "foreground"
    
  - name: "version_text"
    type: "text"
    params:
      text: "v2.0 - Feature Showcase"
      font_size: 24
      color: "#888888"
    position: [0, 0.5, 0]
    
  # ============ BASIC SHAPES ============
  - name: "circle_basic"
    type: "shape"
    params:
      shape_type: "circle"
      radius: 1.5
      color: "#FF6B6B"
      fill_opacity: 0.8
      stroke_width: 4
    position: [-6, 0, 0]
    
  - name: "square_basic"
    type: "shape"
    params:
      shape_type: "square"
      side_length: 2.5
      color: "#4ECDC4"
      fill_opacity: 0.8
      stroke_width: 4
    position: [-2, 0, 0]
    
  - name: "polygon_basic"
    type: "shape"
    params:
      shape_type: "polygon"
      vertices: 8
      radius: 1.5
      color: "#9B59B6"
      fill_opacity: 0.8
      stroke_width: 4
    position: [2, 0, 0]
    
  - name: "triangle_basic"
    type: "shape"
    params:
      shape_type: "polygon"
      vertices: 3
      radius: 1.5
      color: "#F39C12"
      fill_opacity: 0.8
      stroke_width: 4
    position: [6, 0, 0]
    
  # ============ TEXT VARIATIONS ============
  - name: "gradient_text"
    type: "text"
    params:
      text: "Gradient Text"
      font_size: 36
      gradient: ["#FF0000", "#FFFF00", "#00FF00", "#00FFFF", "#0000FF"]
    position: [-4, -3, 0]
    
  - name: "italic_text"
    type: "text"
    params:
      text: "Italic Style"
      font_size: 36
      color: "#E74C3C"
      font_style: "ITALIC"
    position: [0, -3, 0]
    
  - name: "bold_text"
    type: "text"
    params:
      text: "BOLD TEXT"
      font_size: 36
      color: "#2ECC71"
      weight: "BOLD"
    position: [4, -3, 0]
    
  # ============ GROUPS ============
  - name: "shape_group"
    type: "group"
    params:
      position: [0, -5, 0]
    
  # ============ VISUAL ARRAYS ============
  - name: "hex_array"
    type: "visual_array"
    params:
      values: [255, 128, 64, 32, 16, 8, 4, 2, 1]
      display_format: "hex"
      show_indices: true
      cell_width: 1.2
      cell_height: 0.8
      fill_color: "#2ECC71"
      text_color: "#FFFFFF"
    position: [0, -2, 0]
    
  - name: "binary_array"
    type: "visual_array"
    params:
      values: [1, 0, 1, 1, 0, 1, 0, 1]
      display_format: "binary"
      labels: ["B7", "B6", "B5", "B4", "B3", "B2", "B1", "B0"]
      cell_width: 0.8
      cell_height: 0.8
      fill_color: "#3498DB"
      text_color: "#FFFFFF"
    position: [0, -3.5, 0]
    
  - name: "decimal_array"
    type: "visual_array"
    params:
      values: [10, 20, 30, 40, 50]
      display_format: "decimal"
      show_indices: false
      cell_width: 1.5
      cell_height: 1.0
      fill_color: "#9B59B6"
      text_color: "#FFFFFF"
      orientation: "vertical"
    position: [-8, -2, 0]
    
  # ============ CAD OBJECTS ============
  - name: "rounded_rect"
    type: "rounded_shape"
    params:
      shape: "rectangle"
      width: 4
      height: 2
      corner_radius: 0.4
      color: "#00FF88"
      stroke_width: 3
      fill_opacity: 0.2
    position: [-4, 2, 0]
    
  - name: "chamfered_hex"
    type: "chamfered_shape"
    params:
      shape: "polygon"
      n: 6
      radius: 1.5
      chamfer_offset: 0.3
      color: "#FF8800"
      stroke_width: 3
      fill_opacity: 0.2
    position: [4, 2, 0]
    
  - name: "hatched_circle"
    type: "hatched_shape"
    params:
      shape: "circle"
      radius: 1.2
      color: "#FF00FF"
      stroke_width: 2
      fill_opacity: 0
      hatch_angle: 0.785398
      hatch_spacing: 0.15
    position: [0, 2, 0]
    
  - name: "dashed_square"
    type: "dashed_shape"
    params:
      shape: "square"
      side_length: 2
      num_dashes: 16
      dashed_ratio: 0.7
      color: "#00FFFF"
      stroke_width: 3
    position: [0, -6, 0]

animations:
  # ======== OPENING SEQUENCE (0-10s) ========
  - target: "main_title"
    animation_type: "write"
    start_time: 0
    duration: 2.5
    
  - target: "subtitle"
    type: "fadein"
    start_time: 1.5
    duration: 1.5
    params:
      shift: [0, 0.5, 0]
      
  - target: "version_text"
    type: "fadein"
    start_time: 2.5
    duration: 1
    
  # ======== BASIC SHAPES (10-25s) ========
  - target: "circle_basic"
    type: "create"
    start_time: 5
    duration: 1
    
  - target: "square_basic"
    type: "create"
    start_time: 5.3
    duration: 1
    
  - target: "polygon_basic"
    type: "create"
    start_time: 5.6
    duration: 1
    
  - target: "triangle_basic"
    type: "create"
    start_time: 5.9
    duration: 1
    
  # Shape animations
  - target: "circle_basic"
    type: "rotate"
    start_time: 8
    duration: 2
    params:
      angle: 6.28318
      
  - target: "square_basic"
    type: "scale"
    start_time: 8.5
    duration: 2
    params:
      factor: 1.5
      
  - target: "polygon_basic"
    type: "rotate"
    start_time: 9
    duration: 2
    params:
      angle: -6.28318
      
  - target: "triangle_basic"
    type: "indicate"
    start_time: 9.5
    duration: 1
    params:
      scale_factor: 1.3
      color: "#FFFF00"
      
  # ======== TEXT VARIATIONS (25-35s) ========
  - target: "gradient_text"
    type: "write"
    start_time: 12
    duration: 1.5
    
  - target: "italic_text"
    type: "write"
    start_time: 13
    duration: 1.5
    
  - target: "bold_text"
    type: "write"
    start_time: 14
    duration: 1.5
    
  # ======== VISUAL ARRAYS (35-50s) ========
  - target: "hex_array"
    type: "create"
    start_time: 17
    duration: 2
    
  - target: "binary_array"
    type: "create"
    start_time: 18
    duration: 1.5
    
  - target: "decimal_array"
    type: "create"
    start_time: 19
    duration: 1.5
    
  # ======== CAD OBJECTS (50-65s) ========
  - target: "rounded_rect"
    type: "create"
    start_time: 22
    duration: 1.5
    
  - target: "chamfered_hex"
    type: "create"
    start_time: 23
    duration: 1.5
    
  - target: "hatched_circle"
    type: "fadein"
    start_time: 24
    duration: 1.5
    
  - target: "dashed_square"
    type: "create"
    start_time: 25
    duration: 1.5
    
  # CAD rotations
  - target: "rounded_rect"
    type: "rotate"
    start_time: 27
    duration: 2
    params:
      angle: 1.5708
      
  - target: "chamfered_hex"
    type: "rotate"
    start_time: 27.5
    duration: 2
    params:
      angle: 3.14159
      
  - target: "hatched_circle"
    type: "rotate"
    start_time: 28
    duration: 2
    params:
      angle: -1.5708
      
  # ======== TRANSFORMATIONS (65-80s) ========
  - target: "circle_basic"
    type: "transform"
    start_time: 32
    duration: 2
    params:
      to_shape: "square"
      side_length: 2.5
      
  - target: "square_basic"
    type: "transform"
    start_time: 34
    duration: 2
    params:
      to_shape: "circle"
      radius: 1.8
      
  # ======== MOVEMENTS (80-90s) ========
  - target: "polygon_basic"
    type: "move"
    start_time: 37
    duration: 2
    params:
      to: [0, 0, 0]
      
  - target: "triangle_basic"
    type: "move"
    start_time: 38
    duration: 2
    params:
      to: [-3, -4, 0]
      
  # ======== FADE SEQUENCES (90-100s) ========
  - target: "gradient_text"
    type: "fadeout"
    start_time: 42
    duration: 0.5
    
  - target: "italic_text"
    type: "fadeout"
    start_time: 42.3
    duration: 0.5
    
  - target: "bold_text"
    type: "fadeout"
    start_time: 42.6
    duration: 0.5
    
  - target: "hex_array"
    type: "fadeout"
    start_time: 43
    duration: 0.5
    
  - target: "binary_array"
    type: "fadeout"
    start_time: 43.3
    duration: 0.5
    
  - target: "decimal_array"
    type: "fadeout"
    start_time: 43.6
    duration: 0.5
    
  # ======== FINALE (100-120s) ========
  - target: "main_title"
    type: "scale"
    start_time: 45
    duration: 1.5
    params:
      factor: 1.5
      
  - target: "subtitle"
    type: "transform"
    start_time: 47
    duration: 2
    params:
      text: "Thank You!"
      
  # Final cleanup
  - target: "version_text"
    type: "fadeout"
    start_time: 50
    duration: 0.5
    
  - target: "circle_basic"
    type: "fadeout"
    start_time: 51
    duration: 0.3
    
  - target: "square_basic"
    type: "fadeout"
    start_time: 51.2
    duration: 0.3
    
  - target: "polygon_basic"
    type: "fadeout"
    start_time: 51.4
    duration: 0.3
    
  - target: "triangle_basic"
    type: "fadeout"
    start_time: 51.6
    duration: 0.3
    
  - target: "rounded_rect"
    type: "fadeout"
    start_time: 52
    duration: 0.3
    
  - target: "chamfered_hex"
    type: "fadeout"
    start_time: 52.2
    duration: 0.3
    
  - target: "hatched_circle"
    type: "fadeout"
    start_time: 52.4
    duration: 0.3
    
  - target: "dashed_square"
    type: "fadeout"
    start_time: 52.6
    duration: 0.3
    
  - target: "subtitle"
    type: "fadeout"
    start_time: 54
    duration: 1
    
  - target: "main_title"
    type: "fadeout"
    start_time: 55
    duration: 2

effects:
  # Title glow effect
  - type: "glow_effect"
    target: "main_title"
    start_time: 0
    duration: 120
    params:
      color: "#FFD700"
      radius: 20
      intensity: 0.8
      
  # Particle system
  - type: "particle_system"
    start_time: 5
    duration: 15
    params:
      n_emitters: 5
      particles_per_second: 50
      particle_lifetime: 3.0
      velocity_range: [1, 5]
      particle_color: "#FFFFFF"
      particle_radius: 0.02
      
  # Magical circle
  - type: "magical_circle"
    start_time: 22
    duration: 15
    params:
      radius: 4.0
      n_layers: 3
      rune_count: 20
      rotation_speed: 0.5
      pulse_frequency: 1.0
      reveal_style: "spiral"
      glow: true
      color_scheme:
        outer_circle: "#4A90E2"
        inner_circles: "#7B68EE"
        runes: "#9B59B6"
        glow: "#4A90E2"
        
  # Trail effects
  - type: "trail_effect"
    target: "circle_basic"
    start_time: 8
    duration: 2
    params:
      trail_length: 30
      trail_color: "#FF6B6B"
      
  - type: "trail_effect"
    target: "polygon_basic"
    start_time: 9
    duration: 2
    params:
      trail_length: 30
      trail_color: "#9B59B6"
      
  # Ripple effect
  - type: "ripple_effect"
    start_time: 32
    duration: 4
    params:
      center: [0, 0, 0]
      amplitude: 0.3
      frequency: 3
      wavelength: 2
      
  # Fire effect on title at the end
  - type: "fire"
    target: "main_title"
    start_time: 45
    duration: 10
    params:
      flame_height: 1.0
      flame_colors: ["#FF4500", "#FFA500", "#FFD700"]
      intensity: 0.8