scene:
  name: "Manim Studio Showcase"
  description: "A comprehensive demonstration of Manim Studio features"
  duration: 60
  resolution: [1920, 1080]
  fps: 30
  background_color: "#0a0a0a"
  
  objects:
    # Title text
    - name: "main_title"
      type: "text"
      params:
        text: "MANIM STUDIO"
        font_size: 96
        color: "#FFD700"
        weight: "BOLD"
      position: [0, 2, 0]
      
    - name: "subtitle"
      type: "text"
      params:
        text: "Animation Framework"
        font_size: 48
        color: "#CCCCCC"
      position: [0, 0.5, 0]
      
    # Basic shapes
    - name: "circle1"
      type: "shape"
      params:
        shape_type: "circle"
        radius: 1.5
        color: "#FF6B6B"
        fill_opacity: 0.8
        stroke_width: 4
      position: [-5, -2, 0]
      
    - name: "square1"
      type: "shape"
      params:
        shape_type: "square"
        side_length: 2
        color: "#4ECDC4"
        fill_opacity: 0.8
        stroke_width: 4
      position: [0, -2, 0]
      
    - name: "polygon1"
      type: "shape"
      params:
        shape_type: "polygon"
        vertices: 6
        radius: 1.5
        color: "#9B59B6"
        fill_opacity: 0.8
        stroke_width: 4
      position: [5, -2, 0]
      
    # Text variations
    - name: "gradient_text"
      type: "text"
      params:
        text: "Gradient Colors"
        font_size: 36
        gradient: ["#FF0000", "#FFFF00", "#00FF00", "#00FFFF", "#0000FF"]
      position: [-5, 2, 0]
      
    - name: "italic_text"
      type: "text"
      params:
        text: "Italic Style"
        font_size: 36
        color: "#E74C3C"
        font_style: "ITALIC"
      position: [5, 2, 0]
      
    # Visual array
    - name: "array_demo"
      type: "visual_array"
      params:
        values: [10, 20, 30, 40, 50]
        cell_width: 1.2
        cell_height: 0.8
        fill_color: "#2ECC71"
        text_color: "#FFFFFF"
      position: [0, -4, 0]

  animations:
    # Title sequence (0-5s)
    - target: "main_title"
      type: "write"
      start_time: 0
      duration: 2
      
    - target: "subtitle"
      type: "fade_in"
      start_time: 1
      duration: 1.5
      
    # Shapes appear (5-10s)
    - target: "circle1"
      type: "create"
      start_time: 3
      duration: 1
      
    - target: "square1"
      type: "create"
      start_time: 3.5
      duration: 1
      
    - target: "polygon1"
      type: "create"
      start_time: 4
      duration: 1
      
    # Shape animations (10-15s)
    - target: "circle1"
      type: "rotate"
      start_time: 6
      duration: 2
      params:
        angle: 360
        
    - target: "square1"
      type: "scale"
      start_time: 7
      duration: 2
      params:
        factor: 1.5
        
    - target: "polygon1"
      type: "rotate"
      start_time: 8
      duration: 2
      params:
        angle: -360
        
    # Text variations (15-20s)
    - target: "gradient_text"
      type: "write"
      start_time: 11
      duration: 1.5
      
    - target: "italic_text"
      type: "write"
      start_time: 12
      duration: 1.5
      
    # Visual array (20-25s)
    - target: "array_demo"
      type: "create"
      start_time: 14
      duration: 2
      
    # Movement animations (25-35s)
    - target: "circle1"
      type: "move"
      start_time: 17
      duration: 2
      params:
        to: [-5, 0, 0]
        
    - target: "square1"
      type: "move"
      start_time: 18
      duration: 2
      params:
        to: [0, 0, 0]
        
    - target: "polygon1"
      type: "move"
      start_time: 19
      duration: 2
      params:
        to: [5, 0, 0]
        
    # Transform and effects (35-45s)
    - target: "main_title"
      type: "scale"
      start_time: 22
      duration: 1
      params:
        factor: 1.2
        
    - target: "circle1"
      type: "indicate"
      start_time: 24
      duration: 1
      params:
        scale_factor: 1.3
        color: "#FFFF00"
        
    # Fade out sequence (45-60s)
    - target: "gradient_text"
      type: "fade_out"
      start_time: 27
      duration: 0.5
      
    - target: "italic_text"
      type: "fade_out"
      start_time: 27.5
      duration: 0.5
      
    - target: "array_demo"
      type: "fade_out"
      start_time: 28
      duration: 0.5
      
    - target: "subtitle"
      type: "fade_out"
      start_time: 29
      duration: 1
      
    - target: "circle1"
      type: "fade_out"
      start_time: 30
      duration: 0.5
      
    - target: "square1"
      type: "fade_out"
      start_time: 30.5
      duration: 0.5
      
    - target: "polygon1"
      type: "fade_out"
      start_time: 31
      duration: 0.5
      
    - target: "main_title"
      type: "fade_out"
      start_time: 32
      duration: 2