# Manim Studio Ultimate Showcase
# This YAML demonstrates the full capabilities of the system
# Including: 3D, Physics, CAD, Visual Arrays, Effects, and Advanced Animations

scene:
  name: "UltimateShowcase"
  description: "A comprehensive demonstration of all Manim Studio features"
  duration: 120.0
  resolution: [1920, 1080]
  fps: 60
  background_color: "#0a0a0a"
  camera_type: "3d"
  
  # Advanced 3D camera configuration
  camera:
    phi: 1.2  # ~70 degrees in radians
    theta: 5.5  # ~315 degrees in radians (equivalent to -45)
    distance: 20
    focal_point: [0, 0, 0]
    dof_enabled: true
    focal_distance: 15
    aperture: 0.8
    
  # Frame extraction for analysis
  frame_extraction:
    enabled: true
    frame_interval: 300
    analyze: true
    keyframe_extraction: true
    keyframe_threshold: 0.8
    generate_report: true

  # Scene objects organized by category
  objects:
    # ============ TITLE SEQUENCE ============
    - name: "title_text"
      type: "text"
      layer: "foreground"
      params:
        text: "MANIM STUDIO"
        position: [0, 3, 0]
        font: "Arial"
        weight: "BOLD"
        font_size: 72
        gradient: ["#FFD700", "#FF6B6B", "#4ECDC4"]
        opacity: 0
        
    - name: "subtitle"
      type: "text"
      layer: "foreground"
      params:
        text: "Ultimate Feature Showcase"
        position: [0, 2, 0]
        font: "Arial"
        font_size: 36
        color: "#CCCCCC"
        opacity: 0
        
    # ============ 3D OBJECTS ============
    - name: "coordinate_axes"
      type: "axes_3d"
      layer: "background"
      params:
        x_range: [-8, 8, 1]
        y_range: [-6, 6, 1]
        z_range: [-4, 4, 1]
        position: [0, 0, 0]
        opacity: 0.3
        
    - name: "grid_floor"
      type: "grid_3d"
      layer: "background"
      params:
        size: [20, 20]
        position: [0, 0, -3]
        color: "#1a1a2e"
        opacity: 0.5
        
    - name: "demo_cube"
      type: "cube"
      params:
        side_length: 2
        position: [-5, 0, 0]
        color: "#FF6B6B"
        fill_opacity: 0.8
        
    - name: "demo_sphere"
      type: "sphere"
      params:
        radius: 1.5
        position: [5, 0, 0]
        color: "#4ECDC4"
        resolution: [32, 32]
        
    # ============ PHYSICS OBJECTS ============
    - name: "pendulum_system"
      type: "physics.pendulum"
      params:
        position: [-8, 4, 0]
        length: 3
        mass: 1
        angle: 45
        gravity: 9.8
        damping: 0.1
        color: "#FFD700"
        auto_update: true
        
    - name: "spring_system"
      type: "physics.spring"
      params:
        position: [8, 2, 0]
        length: 2
        k: 10
        mass: 0.5
        displacement: 1
        damping: 0.2
        color: "#9B59B6"
        auto_update: true
        
    # ============ CAD OBJECTS ============
    - name: "technical_drawing"
      type: "rounded_shape"
      params:
        vertices: [[0, 0, 0], [4, 0, 0], [4, 3, 0], [0, 3, 0]]
        corner_radius: 0.3
        position: [-2, -4, 0]
        stroke_color: "#00FF00"
        stroke_width: 2
        fill_opacity: 0
        
    - name: "chamfered_box"
      type: "chamfered_shape"
      params:
        vertices: [[-1, -1, 0], [1, -1, 0], [1, 1, 0], [-1, 1, 0]]
        chamfer_offset: 0.2
        position: [2, -4, 0]
        fill_color: "#FF00FF"
        fill_opacity: 0.7
        
    - name: "dimension_line"
      type: "linear_dimension"
      params:
        start: [-4, -6, 0]
        end: [4, -6, 0]
        text: "8.0 units"
        offset: 0.5
        color: "#FFAA00"
        
    # ============ VISUAL ARRAYS ============
    - name: "data_array"
      type: "visual_array"
      params:
        data: [255, 128, 64, 32, 16, 8, 4, 2, 1]
        position: [0, -2, 2]
        display_format: "hex"
        show_indices: true
        orientation: "horizontal"
        cell_width: 1.2
        cell_height: 0.8
        fill_color: "#2ECC71"
        text_color: "#FFFFFF"
        
    - name: "binary_array"
      type: "visual_array"
      params:
        data: [1, 0, 1, 1, 0, 1, 0, 1]
        position: [0, -3, 2]
        display_format: "binary"
        labels: ["B7", "B6", "B5", "B4", "B3", "B2", "B1", "B0"]
        orientation: "horizontal"
        cell_width: 0.8
        fill_color: "#3498DB"
        
    # ============ MATHEMATICAL OBJECTS ============
    - name: "hyperplane_3d"
      type: "hyperplane_3d"
      params:
        normal: [1, 1, 1]
        bias: 0
        position: [0, 0, 0]
        width: 8
        height: 8
        color: "#E74C3C"
        opacity: 0.3
        
    - name: "svm_boundary"
      type: "svm_2d"
      params:
        weights: [0.7, 0.7]
        bias: -2
        margin: 1
        position: [0, 0, 4]
        width: 6
        height: 6
        color: "#F39C12"
        
    # ============ PARTICLE SYSTEM ============
    - name: "particle_emitter"
      type: "particle_system_3d"
      params:
        position: [0, 0, 0]
        num_particles: 100
        lifetime: 3
        emission_rate: 20
        initial_velocity: [0, 5, 0]
        velocity_variance: [2, 1, 2]
        color: "#FFFFFF"
        size: 0.1
        
    # ============ MAGICAL EFFECTS OBJECTS ============
    - name: "magic_circle"
      type: "group"
      params:
        position: [0, 5, -2]
        objects:
          - type: "shape"
            params:
              shape_type: "circle"
              radius: 2
              stroke_color: "#9B59B6"
              stroke_width: 3
              fill_opacity: 0

  # Animation timeline with showcasing all features
  animations:
    # ======== OPENING SEQUENCE ========
    - target: "title_text"
      type: "fadein"
      start_time: 0
      duration: 1
      params:
        shift: [0, -0.5, 0]
        
    - target: "subtitle"
      type: "fadein"
      start_time: 0.5
      duration: 1
      params:
        shift: [0, -0.3, 0]
        
    - target: "coordinate_axes"
      type: "fadein"
      start_time: 1
      duration: 1.5
      
    - target: "grid_floor"
      type: "create"
      start_time: 1.5
      duration: 2
      
    # ======== CAMERA MOVEMENTS ========
    - target: "camera"
      type: "orbit"
      start_time: 2
      duration: 3
      params:
        center: [0, 0, 0]
        radius: 20
        angle: 45
        
    # ======== 3D OBJECTS SHOWCASE ========
    - target: "demo_cube"
      type: "create"
      start_time: 3
      duration: 1
      
    - target: "demo_cube"
      type: "rotate"
      start_time: 4
      duration: 2
      params:
        angle: 360
        axis: [1, 1, 0]
        
    - target: "demo_sphere"
      type: "fadein"
      start_time: 3.5
      duration: 1
      
    - target: "demo_sphere"
      type: "scale"
      start_time: 5
      duration: 1.5
      params:
        factor: 1.5
        
    # ======== PHYSICS DEMONSTRATION ========
    - target: "pendulum_system"
      type: "create"
      start_time: 6
      duration: 1
      
    - target: "spring_system"
      type: "create"
      start_time: 6.5
      duration: 1
      
    # ======== CAD FEATURES ========
    - target: "technical_drawing"
      type: "cad_create"
      start_time: 8
      duration: 2
      params:
        style: "technical"
        
    - target: "chamfered_box"
      type: "cad_trace"
      start_time: 9
      duration: 1.5
      
    - target: "dimension_line"
      type: "write"
      start_time: 10
      duration: 1
      
    # ======== VISUAL ARRAYS ========
    - target: "data_array"
      type: "create"
      start_time: 11
      duration: 1.5
      
    - target: "binary_array"
      type: "create"
      start_time: 12
      duration: 1
      
    # ======== MATHEMATICAL VISUALIZATIONS ========
    - target: "hyperplane_3d"
      type: "fadein"
      start_time: 13
      duration: 2
      
    - target: "hyperplane_3d"
      type: "rotate"
      start_time: 15
      duration: 3
      params:
        angle: 180
        axis: [0, 1, 0]
        
    - target: "svm_boundary"
      type: "create"
      start_time: 14
      duration: 1.5
      
    # ======== PARTICLE EFFECTS ========
    - target: "particle_emitter"
      type: "create"
      start_time: 16
      duration: 0.1
      
    # ======== MAGICAL EFFECTS ========
    - target: "magic_circle"
      type: "create"
      start_time: 17
      duration: 1
      
    # ======== COMPLEX CAMERA SEQUENCE ========
    - target: "camera"
      type: "fly_through"
      start_time: 18
      duration: 5
      params:
        waypoints:
          - position: [10, 5, 15]
            look_at: [0, 0, 0]
          - position: [0, 10, 10]
            look_at: [-5, 0, 0]
          - position: [-10, 5, 15]
            look_at: [5, 0, 0]
          - position: [0, 0, 20]
            look_at: [0, 0, 0]
        easing: "ease_in_out"
        
    # ======== TRANSFORMATIONS ========
    - target: "demo_cube"
      type: "transform"
      start_time: 20
      duration: 2
      params:
        to: "demo_sphere"
        
    - target: "title_text"
      type: "move"
      start_time: 22
      duration: 1
      params:
        to: [0, -5, 0]
        
    - target: "subtitle"
      type: "fadeout"
      start_time: 22
      duration: 1
      
    # ======== FINALE WITH EFFECTS ========
    - target: "camera"
      type: "dolly_zoom"
      start_time: 23
      duration: 3
      params:
        zoom_factor: 0.5
        dolly_distance: 10
        
    - target: "title_text"
      type: "write"
      start_time: 24
      duration: 2
      params:
        text: "The End"

  # Advanced effects applied throughout
  effects:
    # Glow effect on title
    - target: "title_text"
      type: "glow_effect"
      start_time: 0
      duration: 120
      params:
        color: "#FFD700"
        radius: 10
        intensity: 0.8
        
    # Particle system for magic circle
    - target: "magic_circle"
      type: "magical_circle"
      start_time: 17
      duration: 10
      params:
        rotation_speed: 30
        pulse_frequency: 2
        rune_count: 8
        
    # Physics gravity effect
    - target: "pendulum_system"
      type: "gravity_effect"
      start_time: 7
      duration: 15
      params:
        gravity_strength: 9.8
        direction: [0, -1, 0]
        
    # Spring oscillation
    - target: "spring_system"
      type: "oscillation_effect"
      start_time: 7.5
      duration: 15
      params:
        frequency: 2
        amplitude: 0.5
        
    # Technical drawing style
    - target: "technical_drawing"
      type: "technical_drawing"
      start_time: 8
      duration: 120
      params:
        style: "blueprint"
        
    # Cross hatching on CAD object
    - target: "chamfered_box"
      type: "cross_hatch"
      start_time: 9
      duration: 120
      params:
        density: 20
        angle: 45
        
    # Neon effect on arrays
    - target: "data_array"
      type: "neon_effect"
      start_time: 11
      duration: 120
      params:
        color: "#00FF00"
        intensity: 1.5
        
    # Ripple effect
    - target: "hyperplane_3d"
      type: "ripple_effect"
      start_time: 15
      duration: 5
      params:
        center: [0, 0, 0]
        wavelength: 2
        amplitude: 0.2
        speed: 1
        
    # Particle morph effect
    - target: "demo_cube"
      type: "particle_morph_effect"
      start_time: 20
      duration: 2
      params:
        particle_count: 1000
        
    # Lens flare
    - target: "camera"
      type: "lens_flare_effect"
      start_time: 23
      duration: 3
      params:
        position: [0, 5, 0]
        intensity: 2
        color: "#FFFFFF"
        
    # Depth of field focus pull
    - target: "camera"
      type: "focus_pull_effect"
      start_time: 25
      duration: 2
      params:
        from_distance: 20
        to_distance: 5
        
    # Final particle explosion
    - target: "title_text"
      type: "particle_system"
      start_time: 26
      duration: 2
      params:
        explosion: true
        particle_count: 500
        speed: 10
        colors: ["#FFD700", "#FF6B6B", "#4ECDC4", "#9B59B6"]